name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.27.1']
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        working-directory: ./event-logger
        run: go version
      - name: List directory
        run: ls -l
      - name: Run producer tests
        run: cd ./event-logger/producer && go test
